version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pombola
    depends_on:
      - db
    volumes:
      - ./data:/app-data
      - .:/app
    environment:
      - DATABASE_URL=postgresql://pombola:pombola@db/pombola
      - DATABASE_NAME=pombola
      - POMBOLA_DATADIR=/app-data
      - DJANGO_DEBUG=TRUE
      - DJANGO_SECRET_KEY=not-secret-in-dev
      - ELASTICSEARCH_URL=elasticsearch:9200
      - GOOGLE_MAPS_GEOCODING_API_KEY=${GOOGLE_MAPS_GEOCODING_API_KEY}
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  db:
    build:
      context: docker/db
    image: postgres-9.6-postgis-2.3
    environment:
      - POSTGRES_USER=pombola
      - POSTGRES_PASSWORD=pombola
      - POSTGRES_DB=pombola
    volumes:
      - db-data:/var/lib/postgresql/data

  elasticsearch:
    image: elastic
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  db-data:
  es-data:
